// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/test.proto

package com.xue.bigdata.test.protobuf;

public interface TestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Test)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated string names = 2;</code>
   * @return A list containing the names.
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <code>repeated string names = 2;</code>
   * @return The count of names.
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the element to return.
   * @return The names at the given index.
   */
  java.lang.String getNames(int index);
  /**
   * <code>repeated string names = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the names at the given index.
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);

  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  int getSiMapCount();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  boolean containsSiMap(
      java.lang.String key);
  /**
   * Use {@link #getSiMapMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.Integer>
  getSiMap();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.Integer>
  getSiMapMap();
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */

  int getSiMapOrDefault(
      java.lang.String key,
      int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; si_map = 7;</code>
   */

  int getSiMapOrThrow(
      java.lang.String key);
}
